[package]
name = "ftp-server2"
version = "0.1.0"
authors = ["Carlos B <carlos.baezruiz@gmail.com>"]


[dependencies]
bytes = "^0.4.5"
tokio-core = "^0.1.10"
tokio-io = "^0.1.3"
time = "0.1.38"
futures-await={git =  "https://github.com/alexcrichton/futures-await" }


