[package]
name = "example_capnprot"
version = "0.1.0"
authors = ["carlosb"]
build = "build.rs"
edition = "2018"

[build-dependencies]
capnpc = "0.7.2"

[dependencies]
capnpc = "0.7.4"
capnp-rpc = "0.7.4"
gj = "0.2"
gjio = "0.1"
