http_python:
        input:
                host: 0.0.0.0
                port: 8000
        output:
                host: 0.0.0.0
                port: 8081

http_python2:
        input:
                host: 0.0.0.0
                port: 8001
        output:
                host: 0.0.0.0
                port: 8082
