[package]
name = "cargo"
version = "0.1.0"
authors = ["Carlos B <carlos.baezruiz@gmail.com>"]
edition = "2018"


[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.5", default-features= false }

[lib]
crate-type=["dylib"]

